/**
 * AI matchup previews. Once a week (Wednesday morning) — or on demand from /admin — every matchup
 * of the current week gets a columnist-style write-up generated by the Anthropic API with web
 * search turned on for real NFL context (injuries, byes, streaks). Results are stored in Blobs so
 * pages only ever read them; nothing is generated on page load.
 *
 * Storage: previews/<season>/<week>.json → PreviewSet. While a regeneration runs, the previous
 * previews stay in the file (status: running) so the site never goes blank mid-refresh.
 */
import Anthropic from '@anthropic-ai/sdk';
import { db, env, getDerived, getDraftRecap, getRankings, getSnapshot, KEYS } from './store';
import type { Derived, DraftRecap, Matchup, Rankings, Snapshot, Team } from './types';
import type { HistoryGame } from './analytics';
import { fmt1, teamById } from './format';

export interface PreviewPlayer {
  name: string;
  pos: string;
  why: string;
}

export interface AiPreview {
  matchupId: number;
  week: number;
  homeId: number;
  awayId: number;
  headline: string;
  body: string; // paragraphs separated by blank lines
  keyPlayers: { home: PreviewPlayer[]; away: PreviewPlayer[] };
  prediction: { winnerId: number; winProb: number; reasoning: string };
  bold: string;
  sources: { title: string; url: string }[];
  generatedAt: string;
  error?: string; // set when this matchup's generation failed
}

export interface PreviewSet {
  season: number;
  week: number;
  status: 'running' | 'ready' | 'error';
  startedAt: string;
  finishedAt: string | null;
  model: string;
  error: string | null;
  previews: AiPreview[];
}

export const previewKey = (season: number, week: number) => `previews/${season}/${week}.json`;

export const getPreviewSet = (season: number, week: number, strong = false) => db.get<PreviewSet>(previewKey(season, week), { strong });

export function previewsConfigured(): boolean {
  return Boolean(env('ANTHROPIC_API_KEY'));
}

const MODEL = () => env('ANTHROPIC_MODEL') || 'claude-sonnet-5';
const SEARCHES_PER_MATCHUP = 6;
const CONCURRENCY = 3;

/** First sentence or two of the preview body, for teaser cards. */
export function teaser(body: string, max = 230): string {
  const first = body.split(/\n+/)[0] ?? '';
  const sentences = first.split(/(?<=[.!?…])\s+/);
  let out = sentences[0] ?? '';
  if (sentences[1] && (out + ' ' + sentences[1]).length <= max) out += ' ' + sentences[1];
  return out.length > max ? out.slice(0, max - 1).trimEnd() + '…' : out;
}

// ---------- context building ----------

interface Ctx {
  snap: Snapshot;
  derived: Derived | null;
  rankings: Rankings;
  draft: DraftRecap | null;
  history: { season: number; games: HistoryGame[] }[];
  week: number;
}

function teamResults(snap: Snapshot, teamId: number, beforeWeek: number) {
  const out: { week: number; won: boolean | null; pf: number; pa: number; oppId: number }[] = [];
  for (const m of snap.schedule) {
    if (m.week >= beforeWeek || !m.away || m.winner === 'UNDECIDED') continue;
    const home = m.home.teamId === teamId;
    if (!home && m.away.teamId !== teamId) continue;
    const mine = home ? m.home : m.away;
    const theirs = home ? m.away : m.home;
    const won = m.winner === 'TIE' ? null : (m.winner === 'HOME') === home;
    out.push({ week: m.week, won, pf: mine.points, pa: theirs.points, oppId: theirs.teamId });
  }
  return out.sort((a, b) => a.week - b.week);
}

function streak(results: { won: boolean | null }[]): string {
  if (!results.length) return 'none';
  let n = 0;
  const last = results[results.length - 1].won;
  for (let i = results.length - 1; i >= 0 && results[i].won === last; i--) n++;
  return last === null ? `T${n}` : `${last ? 'W' : 'L'}${n}`;
}

function seasonRecord(games: HistoryGame[], teamId: number) {
  let w = 0,
    l = 0,
    t = 0;
  for (const g of games) {
    if (g.playoffTier !== 'NONE') continue;
    if (g.homeId !== teamId && g.awayId !== teamId) continue;
    if (g.winner === 'TIE') t++;
    else if ((g.winner === 'HOME') === (g.homeId === teamId)) w++;
    else l++;
  }
  return w + l + t ? `${w}-${l}${t ? `-${t}` : ''}` : null;
}

function describeTeam(ctx: Ctx, team: Team): string {
  const { snap, derived, rankings, draft, history, week } = ctx;
  const abbr = (id: number) => teamById(snap, id)?.abbrev ?? '?';
  const st = derived?.standings.find((s) => s.teamId === team.id);
  const odds = derived?.odds.find((o) => o.teamId === team.id);
  const weeks = Object.keys(rankings.weeks).map(Number).sort((a, b) => b - a);
  const latest = weeks.length ? rankings.weeks[weeks[0]] : null;
  const pr = latest?.entries.find((r) => r.teamId === team.id);
  const grade = draft?.grades.find((g) => g.teamId === team.id);
  const results = teamResults(snap, team.id, week);
  const lines: string[] = [];
  lines.push(`TEAM: ${team.name} (${team.abbrev}) — record ${team.wins}-${team.losses}${team.ties ? `-${team.ties}` : ''}${st && results.length ? `, ${fmt1(st.ppg)} PPG, standings seed ${st.seed}, all-play ${st.allPlayWins}-${st.allPlayLosses}, luck ${st.luck > 0 ? '+' : ''}${fmt1(st.luck)} wins vs expectation` : ''}`);
  if (pr) lines.push(`Power rank: #${pr.rank}${pr.prevRank ? ` (was #${pr.prevRank})` : ''}`);
  if (odds) lines.push(`Playoff odds (simulated): ${Math.round(odds.playoff)}% (bye ${Math.round(odds.bye)}%, title ${Math.round(odds.title)}%)`);
  if (grade) lines.push(`Draft grade: ${grade.grade} (rank ${grade.rank} of ${snap.teams.length})${grade.bestPick ? `; best pick ${grade.bestPick.name}` : ''}${grade.worstPick ? `; worst pick ${grade.worstPick.name}` : ''}`);
  if (results.length) {
    lines.push(`Streak: ${streak(results)}. Recent results (oldest → newest): ` + results.slice(-4).map((r) => `wk${r.week} ${r.won === null ? 'T' : r.won ? 'W' : 'L'} ${fmt1(r.pf)}–${fmt1(r.pa)} vs ${abbr(r.oppId)}`).join('; '));
    const pts = results.map((r) => r.pf);
    lines.push(`Season high ${fmt1(Math.max(...pts))}, low ${fmt1(Math.min(...pts))}`);
  } else {
    lines.push('No games played yet this season.');
  }
  for (const h of history) {
    const rec = seasonRecord(h.games, team.id);
    if (rec) lines.push(`${h.season} regular season: ${rec}`);
  }
  const starters = team.roster.filter((p) => p.starter && p.slotId !== 21).sort((a, b) => a.slotId - b.slotId);
  const bench = team.roster.filter((p) => !p.starter && p.slotId !== 21).sort((a, b) => b.projWeek - a.projWeek);
  const projTotal = starters.reduce((s, p) => s + p.projWeek, 0);
  lines.push(`Projected starting lineup (week ${week}, total proj ${fmt1(projTotal)}): ` + starters.map((p) => `${p.slot} ${p.name} (${p.pos}, ${p.proTeam}) proj ${fmt1(p.projWeek)}${p.injuryStatus && p.injuryStatus !== 'ACTIVE' ? ` [${p.injuryStatus}]` : ''}`).join('; '));
  if (bench.length) lines.push(`Top bench options: ` + bench.slice(0, 4).map((p) => `${p.name} (${p.pos}, ${p.proTeam}) proj ${fmt1(p.projWeek)}${p.injuryStatus && p.injuryStatus !== 'ACTIVE' ? ` [${p.injuryStatus}]` : ''}`).join('; '));
  return lines.join('\n');
}

function describeSeries(ctx: Ctx, homeId: number, awayId: number): string {
  const { snap, history, week } = ctx;
  let hw = 0,
    aw = 0,
    t = 0;
  const meetings: string[] = [];
  const add = (season: number, wk: number, hId: number, hp: number, ap: number, winner: string) => {
    const homeIsHome = hId === homeId;
    const hPts = homeIsHome ? hp : ap;
    const aPts = homeIsHome ? ap : hp;
    if (winner === 'TIE') t++;
    else if ((winner === 'HOME') === homeIsHome) hw++;
    else aw++;
    meetings.push(`${season} wk${wk}: ${fmt1(hPts)}–${fmt1(aPts)}`);
  };
  for (const h of history) for (const g of h.games) if ((g.homeId === homeId && g.awayId === awayId) || (g.homeId === awayId && g.awayId === homeId)) add(h.season, g.week, g.homeId, g.homePts, g.awayPts, g.winner);
  for (const m of snap.schedule) {
    if (m.week >= week || !m.away || m.winner === 'UNDECIDED') continue;
    if ((m.home.teamId === homeId && m.away.teamId === awayId) || (m.home.teamId === awayId && m.away.teamId === homeId)) add(snap.season, m.week, m.home.teamId, m.home.points, m.away.points, m.winner);
  }
  const home = teamById(snap, homeId)!;
  const away = teamById(snap, awayId)!;
  if (!meetings.length) return `Head-to-head: first meeting on record.`;
  const lead = hw === aw ? `series tied ${hw}-${aw}` : hw > aw ? `${home.abbrev} leads ${hw}-${aw}` : `${away.abbrev} leads ${aw}-${hw}`;
  return `Head-to-head (all-time): ${lead}${t ? ` with ${t} tie(s)` : ''}. Meetings (scores shown ${home.abbrev}–${away.abbrev}): ${meetings.slice(-6).join('; ')}`;
}

function buildPrompt(ctx: Ctx, m: Matchup): string {
  const { snap, derived, week } = ctx;
  const home = teamById(snap, m.home.teamId)!;
  const away = teamById(snap, m.away!.teamId)!;
  const pv = derived?.previews.find((p) => p.matchupId === m.id);
  const playoffWeek = week > snap.regularSeasonWeeks;
  const parts: string[] = [];
  parts.push(`LEAGUE: WSB Generations League — 12-team ESPN fantasy football league of longtime friends, half-PPR, ${snap.regularSeasonWeeks}-week regular season, 6 playoff spots (top 2 get byes). Season ${snap.season}, this is week ${week}${playoffWeek ? ' (PLAYOFFS)' : week === 1 ? ' (season opener)' : ''}.`);
  parts.push(`MATCHUP: ${home.name} vs ${away.name}.` + (pv ? ` ESPN projects ${home.abbrev} ${fmt1(pv.home.projected)} – ${away.abbrev} ${fmt1(pv.away?.projected ?? 0)} (edge ${pv.edge > 0 ? home.abbrev : away.abbrev} by ${fmt1(Math.abs(pv.edge))}).${pv.gameOfWeek ? ' This is the site\'s Game of the Week.' : ''}` : '') + (typeof m.home.winProb === 'number' ? ` ESPN win probability: ${home.abbrev} ${Math.round(m.home.winProb * 100)}%.` : ''));
  parts.push(describeTeam(ctx, home));
  parts.push(describeTeam(ctx, away));
  parts.push(describeSeries(ctx, home.id, away.id));
  return parts.join('\n\n');
}

const SYSTEM = `You are the resident columnist for the WSB Generations League, a 12-team fantasy football league of longtime friends. Every week you write a preview for each matchup. Your voice: fun, confident, a little biting — think a beat writer who has watched these teams for years and has zero patience for a bad lineup decision. Playful trash talk is encouraged: roast teams for their performance, their lineup choices, their draft, their luck, their history. Keep it in the spirit of friends ribbing each other — never mean about the actual people behind the teams, and never comment on anyone's personal life. Refer to teams by their team names (or abbreviations), not by owner names.

You are given the league's own data (records, form, rosters, projections, head-to-head history). Use web search to add real NFL context for the players involved this week: injuries and game statuses, teams on bye, hot and cold streaks, and favorable or unfavorable NFL matchups. Weave that in naturally ("with Chase on bye, X is leaning hard on...") and only state NFL facts you actually found — if you can't confirm something, leave it out rather than guess. Be careful: the NFL season is ${new Date().getFullYear()}; make sure anything you cite is about the current week, not last year.

Output requirements (send them via the submit_preview tool when you are done researching):
- headline: punchy, 4–10 words, no trailing period.
- body: 150–250 words in 2–4 short paragraphs covering the storyline, both teams' recent form, and anything notable (streaks, revenge games, playoff implications, head-to-head history). Plain text, paragraphs separated by a blank line, no markdown, no bullet points.
- keyPlayers: 2 per side, each with one crisp line on why they matter this week.
- prediction: the winner, a win percentage (as a whole number 50–90), and 1–2 sentences of reasoning.
- bold: one bold prediction for the matchup — specific and fun.
- sources: the web pages you actually relied on for NFL context (title + url). Include every page you used.`;

const SUBMIT_TOOL: Anthropic.Tool = {
  name: 'submit_preview',
  description: 'Submit the finished matchup preview. Call this exactly once, after research is complete.',
  input_schema: {
    type: 'object',
    properties: {
      headline: { type: 'string' },
      body: { type: 'string' },
      keyPlayers: {
        type: 'object',
        properties: {
          home: { type: 'array', items: { type: 'object', properties: { name: { type: 'string' }, pos: { type: 'string' }, why: { type: 'string' } }, required: ['name', 'pos', 'why'] } },
          away: { type: 'array', items: { type: 'object', properties: { name: { type: 'string' }, pos: { type: 'string' }, why: { type: 'string' } }, required: ['name', 'pos', 'why'] } },
        },
        required: ['home', 'away'],
      },
      prediction: {
        type: 'object',
        properties: { winner: { type: 'string', description: 'Exact team name of the predicted winner' }, winProb: { type: 'number' }, reasoning: { type: 'string' } },
        required: ['winner', 'winProb', 'reasoning'],
      },
      bold: { type: 'string' },
      sources: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, url: { type: 'string' } }, required: ['title', 'url'] } },
    },
    required: ['headline', 'body', 'keyPlayers', 'prediction', 'bold', 'sources'],
  },
};

// ---------- generation ----------

async function generateOne(client: Anthropic, ctx: Ctx, m: Matchup): Promise<AiPreview> {
  const home = teamById(ctx.snap, m.home.teamId)!;
  const away = teamById(ctx.snap, m.away!.teamId)!;
  const base: AiPreview = {
    matchupId: m.id,
    week: ctx.week,
    homeId: home.id,
    awayId: away.id,
    headline: '',
    body: '',
    keyPlayers: { home: [], away: [] },
    prediction: { winnerId: home.id, winProb: 50, reasoning: '' },
    bold: '',
    sources: [],
    generatedAt: new Date().toISOString(),
  };
  const messages: Anthropic.MessageParam[] = [{ role: 'user', content: `${buildPrompt(ctx, m)}\n\nResearch the NFL context for the key players on both sides (a handful of searches is plenty), then write the preview and submit it with submit_preview.` }];
  const tools: Anthropic.ToolUnion[] = [{ type: 'web_search_20250305', name: 'web_search', max_uses: SEARCHES_PER_MATCHUP } as any, SUBMIT_TOOL];
  const cited = new Map<string, string>();

  for (let turn = 0; turn < 3; turn++) {
    const res = await client.messages.create({ model: MODEL(), max_tokens: 4000, system: SYSTEM, tools, messages }, { timeout: 240_000 });
    // Collect web citations from any text blocks so sources are complete
    for (const block of res.content as any[]) {
      if (block.type === 'text') for (const c of block.citations ?? []) if (c.type === 'web_search_result_location' && c.url) cited.set(c.url, c.title ?? c.url);
    }
    const call = res.content.find((b): b is Anthropic.ToolUseBlock => b.type === 'tool_use' && b.name === 'submit_preview');
    if (call) {
      const input: any = call.input ?? {};
      const winnerName = String(input.prediction?.winner ?? '').toLowerCase();
      const winnerId = winnerName && (away.name.toLowerCase() === winnerName || away.abbrev.toLowerCase() === winnerName || (winnerName.includes(away.name.toLowerCase()) && !winnerName.includes(home.name.toLowerCase()))) ? away.id : home.id;
      let prob = Number(input.prediction?.winProb);
      if (!isFinite(prob)) prob = 55;
      if (prob <= 1) prob *= 100;
      prob = Math.min(95, Math.max(50, Math.round(prob)));
      const sources = new Map<string, string>();
      for (const s of input.sources ?? []) if (s?.url) sources.set(String(s.url), String(s.title || s.url));
      for (const [url, title] of cited) if (!sources.has(url)) sources.set(url, title);
      const clean = (list: any[]) => (Array.isArray(list) ? list : []).slice(0, 3).map((p) => ({ name: String(p?.name ?? ''), pos: String(p?.pos ?? ''), why: String(p?.why ?? '') })).filter((p) => p.name);
      return {
        ...base,
        headline: String(input.headline ?? '').trim().replace(/\.$/, ''),
        body: String(input.body ?? '').trim(),
        keyPlayers: { home: clean(input.keyPlayers?.home), away: clean(input.keyPlayers?.away) },
        prediction: { winnerId, winProb: prob, reasoning: String(input.prediction?.reasoning ?? '').trim() },
        bold: String(input.bold ?? '').trim(),
        sources: [...sources].map(([url, title]) => ({ url, title })).slice(0, 12),
      };
    }
    if (res.stop_reason === 'max_tokens') throw new Error('Model ran out of room before submitting.');
    // No submission yet — carry the conversation forward and ask for it explicitly.
    messages.push({ role: 'assistant', content: res.content as any });
    messages.push({ role: 'user', content: 'Now submit the finished preview with the submit_preview tool.' });
  }
  throw new Error('Model never called submit_preview.');
}

async function mapLimit<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  const out: R[] = new Array(items.length);
  let next = 0;
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, async () => {
      while (next < items.length) {
        const i = next++;
        out[i] = await fn(items[i]);
      }
    }),
  );
  return out;
}

export interface GenerateResult {
  ok: boolean;
  week: number;
  generated: number;
  failed: number;
  error?: string;
}

/**
 * Generate previews for `week` (default: the current matchup period). Safe to call repeatedly;
 * each run replaces that week's file. Designed for a Netlify background function (long-running).
 */
export async function generatePreviews(opts: { week?: number } = {}): Promise<GenerateResult> {
  const startedAt = new Date().toISOString();
  const snap = await getSnapshot();
  if (!snap) return { ok: false, week: 0, generated: 0, failed: 0, error: 'No league data yet — run an ESPN sync first.' };
  const week = opts.week && opts.week > 0 ? opts.week : snap.currentMatchupPeriod;
  const key = previewKey(snap.season, week);
  const previous = await db.get<PreviewSet>(key, { strong: true });
  const fail = async (error: string): Promise<GenerateResult> => {
    await db.set(key, { season: snap.season, week, status: 'error', startedAt, finishedAt: new Date().toISOString(), model: MODEL(), error, previews: previous?.previews ?? [] } satisfies PreviewSet);
    return { ok: false, week, generated: 0, failed: 0, error };
  };
  if (!previewsConfigured()) return fail('ANTHROPIC_API_KEY is not set in the site\'s environment variables.');

  const matchups = snap.schedule.filter((m) => m.week === week && m.away);
  if (!matchups.length) return fail(`No matchups found for week ${week}.`);

  await db.set(key, { season: snap.season, week, status: 'running', startedAt, finishedAt: null, model: MODEL(), error: null, previews: previous?.previews ?? [] } satisfies PreviewSet);

  const [derived, rankings, draft] = await Promise.all([getDerived(), getRankings(), getDraftRecap()]);
  const history: Ctx['history'] = [];
  for (let s = snap.season - 1; s >= snap.season - 3; s--) {
    const h = await db.get(KEYS.history(s));
    if (h?.games?.length) history.push(h);
  }
  const ctx: Ctx = { snap, derived, rankings, draft, week, history };
  const client = new Anthropic({ apiKey: env('ANTHROPIC_API_KEY'), maxRetries: 2 });

  const previews = await mapLimit(matchups, CONCURRENCY, async (m) => {
    try {
      return await generateOne(client, ctx, m);
    } catch (e: any) {
      const msg = e?.message ?? String(e);
      console.error(`preview failed for matchup ${m.id}:`, msg);
      // Keep last week's good copy for this matchup if we have one, but flag the failure.
      const old = previous?.previews.find((p) => p.matchupId === m.id && !p.error);
      return old ? { ...old, error: msg } : { matchupId: m.id, week, homeId: m.home.teamId, awayId: m.away!.teamId, headline: '', body: '', keyPlayers: { home: [], away: [] }, prediction: { winnerId: m.home.teamId, winProb: 50, reasoning: '' }, bold: '', sources: [], generatedAt: new Date().toISOString(), error: msg };
    }
  });

  const failed = previews.filter((p) => p.error && !p.body).length;
  const generated = previews.filter((p) => !p.error).length;
  const allFailed = generated === 0;
  const firstError = previews.find((p) => p.error)?.error ?? null;
  await db.set(key, {
    season: snap.season,
    week,
    status: allFailed ? 'error' : 'ready',
    startedAt,
    finishedAt: new Date().toISOString(),
    model: MODEL(),
    error: allFailed ? firstError : failed ? `${failed} of ${previews.length} previews failed: ${firstError}` : null,
    previews,
  } satisfies PreviewSet);
  return { ok: !allFailed, week, generated, failed, error: allFailed ? firstError ?? undefined : undefined };
}

/**
 * Kick off the background generator over HTTP (returns as soon as Netlify accepts the job).
 * Used by the weekly scheduler and the admin button.
 */
export async function triggerPreviews(opts: { week?: number } = {}): Promise<{ ok: boolean; status: number; url: string; error?: string }> {
  const base = (env('URL') || env('DEPLOY_PRIME_URL') || 'https://wsbgenerations.com').replace(/\/$/, '');
  const url = `${base}/.netlify/functions/previews-background`;
  const key = env('ADMIN_PASSPHRASE') ?? '';
  if (!key) return { ok: false, status: 0, url, error: 'ADMIN_PASSPHRASE is not set.' };
  try {
    const res = await fetch(url, { method: 'POST', headers: { 'x-admin-key': key, 'Content-Type': 'application/json' }, body: JSON.stringify({ week: opts.week ?? null }) });
    return { ok: res.status === 202 || res.ok, status: res.status, url, error: res.status === 202 || res.ok ? undefined : `Background function returned ${res.status}.` };
  } catch (e: any) {
    return { ok: false, status: 0, url, error: e?.message ?? String(e) };
  }
}

/** For local inspection: the exact data prompt a matchup would get. */
export async function debugPrompt(matchupId?: number): Promise<string> {
  const snap = await getSnapshot();
  if (!snap) return 'no snapshot';
  const week = snap.currentMatchupPeriod;
  const [derived, rankings, draft] = await Promise.all([getDerived(), getRankings(), getDraftRecap()]);
  const history: Ctx['history'] = [];
  for (let s = snap.season - 1; s >= snap.season - 3; s--) {
    const h = await db.get(KEYS.history(s));
    if (h?.games?.length) history.push(h);
  }
  const m = snap.schedule.find((x) => x.week === week && x.away && (!matchupId || x.id === matchupId));
  return m ? buildPrompt({ snap, derived, rankings, draft, week, history }, m) : 'no matchup';
}
